version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: 
                name: npm run test
                no_output_timeout: 30s
                command: npm run test
            - run: npm run lint
            - run: npm run format
workflows:
    build-and-test:
      jobs:
        - build-and-test
